name: C++ Build & Test

on:
  push:
    branches:
      - main  # Запуск при пуше в main
  pull_request:
    branches:
      - main  # Запуск при PR в main
  workflow_dispatch:  # Ручной запуск через GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Обновлённая версия

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++

      - name: Compile program
        run: make -C src

      - name: Save artifact
        uses: actions/upload-artifact@v4  # Обновлённая версия
        with:
          name: compiled-program
          path: programm  # Сохранение бинарника

  test:
    runs-on: ubuntu-latest
    needs: build  # Запуск после успешной сборки

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++

      - name: Run tests
        run: make -C src test
