name: C++ Build & Test

on:
  push:
    branches:
      - main  # Запуск при пуше в main
  pull_request:
    branches:
      - main  # Запуск при PR в main
  workflow_dispatch:  # Ручной запуск через GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Обновлённая версия

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++

      - name: Compile program
        run: make -C src

      - name: Save artifact
        uses: actions/upload-artifact@v4  # Обновлённая версия
        with:
          name: compiled-program
          path: usr/bin/matrix  # Сохранение бинарника
              
  test:
    runs-on: ubuntu-latest
    needs: build  # Запуск после успешной сборки

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++

      - name: Run tests
        run: make -C src test
  
  pack:
    runs-on: ubuntu-latest
    needs: test  # Запуск после успешного теста

    steps:
      - name: Create Debian package
        run: |
          mkdir -p package/DEBIAN
          echo "Package: matrix" >> package/DEBIAN/control
          echo "Version: 1.0" >> package/DEBIAN/control
          echo "Section: base" >> package/DEBIAN/control
          echo "Priority: optional" >> package/DEBIAN/control
          echo "Architecture: amd64" >> package/DEBIAN/control
          echo "Depends: libc6 (13.0.4-32)" >> package/DEBIAN/control
          mkdir -p package/usr/bin
          cp src/programm package/usr/bin/
          dpkg-deb --build package matrix.deb

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: matrix-deb-package
          path: matrix.deb
